version: '3'
services:
  api:
    build:
      context: /api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  frontend:
    build:
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD= nicolas
      - MYSQL_DATABASE= crud
    ports:
      - 5050:5050
    volumes:
      - ./crud/db-data:/var/lib/mysql
